name: CI
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
      id:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 下载组件
        run: |
          pip install gdown
      - name: 下载目标文件
        run: |
          pwd
          cd /home/runner/work/Download-GD-On-Action/Download-GD-On-Action/
          gdown --id "${{ inputs.id }}" -O "${{ inputs.name }}"
          tar -cvpzf ${{ inputs.name }}.tgz .
      - name: 上传
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.name }}
          name: ${{ inputs.name }}-${{ inputs.id }}
          files: /home/runner/work/Download-GD-On-Action/Download-GD-On-Action/${{ inputs.name }}.tgz

